@startuml
class ClaseInscrita {
    + ClaseDeportiva : ClaseDeportiva <<get>> <<set>>
    + ClaseDeportivaId : int <<get>> <<set>>
    + InscripcionClaseDeportiva : InscripcionClaseDeportiva <<get>> <<set>>
    + InscripcionClaseDeportivaId : int <<get>> <<set>>
    + Observaciones : string? <<get>> <<set>>
    + PlazasReservadas : int <<get>> <<set>>
    + Precio : decimal <<get>> <<set>>
}
@enduml
