@startuml
!include .\\Alquiler.puml
!include .\\ApplicationUser.puml
!include .\\ClaseDeportiva.puml
!include .\\Competicion.puml
!include .\\Material.puml
!include .\\MaterialAlquilado.puml
!include .\\MetodoPago.puml
!include .\\TipoDeporte.puml
!include .\\TipoMaterial.puml
@enduml
