@startuml
!include .\\Alquiler.puml
!include .\\ApplicationUser.puml
!include .\\ClaseDeportiva.puml
!include .\\ClaseInscrita.puml
!include .\\Competicion.puml
!include .\\Inscripcion.puml
!include .\\InscripcionClaseDeportiva.puml
!include .\\Material.puml
!include .\\MaterialAlquilado.puml
!include .\\MetodoPago.puml
!include .\\TipoDeporte.puml
!include .\\TipoMaterial.puml
@enduml
