@startuml
class Material {
    + IdMaterial : int <<get>> <<set>>
    + <<required>> NombreMaterial : string <<get>> <<set>>
    + Precio : decimal <<get>> <<set>>
    + Cantidad : int <<get>> <<set>>
    + <<required>> TipoMaterial : TipoMaterial <<get>> <<set>>
    + <<required>> TipoDeporte : TipoDeporte <<get>> <<set>>
    + MaterialesAlquilados : IList<MaterialAlquilado> <<get>> <<set>>
}
@enduml
