@startuml
class TipoDeporte {
    + Id : int <<get>> <<set>>
    + Nombre : string <<get>> <<set>>
    + Descripcion : string? <<get>> <<set>>
    + Competiciones : string? <<get>> <<set>>
    + Pistas : int <<get>> <<set>>
    + Materiales : IList<Material> <<get>> <<set>>
}
@enduml
